---
- name: Install Drush.
  get_url:
    url: "{{ drush_phar_url }}"
    dest: /usr/local/bin/drush
# only if drush does not exist

- name: Ensure Drush is executable.
  file:
    path: /usr/local/bin/drush
    mode: 0755

- name: Install Composer
  get_url:
    url: "{{ composer_phar_url }}"
    dest: /usr/local/bin/composer
  when: drupal_major_version == 8

- name: Ensure Composer is executable.
  file:
    path: /usr/local/bin/composer
    mode: 0755
  when: drupal_major_version == 8
