---
- name: PHP | Add php PPA
  apt_repository:
    repo: 'ppa:ondrej/php'
    state: present
    update_cache: true

- name: PHP | install php packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    "{{ php_packages }}"
