---
- name: configure webservers with apache php
  hosts: testservers
  become: true

  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted

    - name: restart postgres
      service:
        name: postgres
        state: restarted

  tasks:

    - name: remove nginx webserver
      apt:
        name: nginx
        state: absent
        purge: true
      ignore_errors: true

    - name: install apache and php
      apt:
        name: ["apache2", "libapache2-mod-php", "php"]
        update_cache: true
        state: present

    - name: enable mod rewrite
      apache2_module:
        name: rewrite
        state: present
      notify: restart apache

    - name: install postgres packages
      apt:
        name: ["libpq-dev", "postgresql", "python-psycopg2"]
      update_cache: true
      cache_valid_time: 3600
      become: true

    - name: copy configuration file
      copy:
        src: postgresql.conf
        dest: /etc/postgresql/10/main/postgresql.conf
        owner: postgres
        group: postgres
        mode: 0644
      become: true
      notify: restart postgres

    - name: copy client authentication configuration file
      copy:
        src: pg_hba.conf
        dest: /etc/postgresql/10/main/pg_hba.conf
        owner: postgres
        group: postgres
        mode: 0640
      become: true
      notify: restart postgres

    - name: create project locale
      locale_gen:
        name: "{{ locale }}"
      become: true
